import aiohttp
from aiogram import Router, F
from aiogram.filters import CommandStart
from aiogram.types import Message

from aiogram.filters import Command
from loguru import logger
from starlette import status
from tortoise.exceptions import IntegrityError

from app.bot.kbs import run_app, main_kb
from app.config import settings
from app.dao.models import User


router = Router()

@router.message(CommandStart())
async def cmd_start(msg: Message):
    await msg.answer(f"–†–∞–¥—ã —Ç–µ–±—è –≤–∏–¥–µ—Ç—å, {msg.from_user.full_name}! –ù–∞–∂–∏–º–∞–π —Å–∫–æ—Ä–µ–µ –Ω–∞ –∫–Ω–æ–ø–∫—É –∏ –∑–∞–ø—É—Å–∫–∞–π –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ!", reply_markup=main_kb())

@router.message(F.text == "üß†About")
async def get_info(msg: Message):
    await msg.answer("–î–∞–Ω–Ω–æ–µ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ —Å–æ–∑–¥–∞–Ω–æ –≤ –∫–∞—á–µ—Å—Ç–≤–µ –ø—Ä–æ—Ç–æ—Ç–∏–ø–∞ –¥–ª—è –æ–±–º–µ–Ω–∞ —É—á–µ—Ç–Ω—ã–º–∏ –¥–∞–Ω–Ω—ã–º–∏ –º–µ–∂–¥—É –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è–º–∏")

@router.message(F.text == "ü§ëOpen app")
@router.message(Command("open_app"))
async def open_app(msg: Message):
    telegram_id = msg.from_user.id
    username = msg.from_user.full_name
    first_name = msg.from_user.first_name
    last_name = msg.from_user.last_name

    # –°–æ–∑–¥–∞–µ–º –æ–±—ä–µ–∫—Ç User
    user = User(
        telegram_id=telegram_id,
        first_name=first_name,
        last_name=last_name,
        nickname=username
    )

    try:
        # –°–æ—Ö—Ä–∞–Ω—è–µ–º –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –≤ –±–∞–∑—É –¥–∞–Ω–Ω—ã—Ö
        await user.save()
        logger.info(f"–ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å {username}  –¥–æ–±–∞–≤–ª–µ–Ω –≤ –±–¥")
        await msg.answer("Launch app!üöÄ", reply_markup=run_app(telegram_id))
    except IntegrityError:
        # –û–±—Ä–∞–±–æ—Ç–∫–∞ —Å–ª—É—á–∞—è, –µ—Å–ª–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å —É–∂–µ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç
        logger.info(f"–ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å {username} —É–∂–µ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç")
        await msg.answer("Launch app!üöÄ", reply_markup=run_app(telegram_id))
    except Exception as e:
        await msg.answer("Something went wrong. Try again later.")
        logger.error(f"Unexpected error: {e}")